# Generated by Django 4.2.4 on 2023-08-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('FASHION', 'Fashion'), ('BEAUTY', 'Beauty'), ('TRAVEL', 'Travel'), ('PERSONAL', 'Personal'), ('TECH', 'Tech'), ('HEALTH', 'Health'), ('BUSINESS', 'Business'), ('FITNESS', 'Fitness'), ('EDUCATION', 'Education'), ('FOOD', 'Food'), ('ENTERTAINMENT', 'Entertainment')], max_length=512)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
