# Generated by Django 4.2.4 on 2023-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blogwebsite_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwebsite',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
