# Generated by Django 4.2.4 on 2023-08-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blogwebsite_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogwebsite',
            name='image',
            field=models.ImageField(default='images/logo.png', upload_to='images/'),
        ),
    ]
