# Generated by Django 4.2.4 on 2023-08-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle')], max_length=20)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
