# Generated by Django 4.2.4 on 2023-08-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Bootcamp',
            field=models.CharField(choices=[('python', 'python'), ('java', 'java'), ('Data saince', 'Data saince'), ('aws', 'aws')], default='python', max_length=128),
            preserve_default=False,
        ),
    ]
