# Generated by Django 4.2.4 on 2023-08-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/2660eb9838be92ebf87322ef5ebac3ed.jpg', upload_to='images/'),
        ),
    ]
