# Generated by Django 4.2.4 on 2023-08-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blog_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
