# Generated by Django 4.2.4 on 2023-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_newblog_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblog',
            name='category',
            field=models.CharField(choices=[('Business blog', 'Business blog'), ('beauty blog', 'beauty blog'), ('travel blog', 'travel blog'), ('music blog', 'music blog'), ('Fashion blogs', 'Fashion blogs')], max_length=2048),
        ),
    ]
