# Generated by Django 4.2.4 on 2023-08-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recpie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_recipes', models.CharField(max_length=2048)),
                ('category', models.CharField(max_length=2048)),
                ('Ingredients', models.TextField()),
                ('Instructions', models.TextField()),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
