# Generated by Django 4.2.4 on 2023-08-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('LT', 'Literature'), ('IT', 'Technology'), ('FO', 'Food'), ('TR', 'Travel'), ('HE', 'Health')], max_length=50)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
