# Generated by Django 4.2.4 on 2023-08-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Beauty', 'Beauty'), ('Fashion', 'Fashion')], max_length=10),
        ),
    ]
