# Generated by Django 4.2.4 on 2023-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='images/my-recipes-logo.png', upload_to='images/'),
        ),
    ]
