# Generated by Django 4.2.4 on 2023-08-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_description_post_content_remove_post_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Saudi Arabia ', 'Saudi Arabia'), ('Italy', 'Italy'), ('France', 'France'), ('Spain', 'Spain'), ('United States', 'United States')], max_length=128),
        ),
    ]
