# Generated by Django 4.2.4 on 2023-08-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='images/background.jpg', upload_to='images/'),
        ),
    ]
