# Generated by Django 4.2.4 on 2023-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
