# Generated by Django 4.2.4 on 2023-08-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/def.jpg', upload_to='images/'),
        ),
    ]
