# Generated by Django 4.2.4 on 2023-08-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_post_cat_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
