# Generated by Django 4.2.4 on 2023-08-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_postcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='context',
            new_name='content',
        ),
    ]
