# Generated by Django 4.2.4 on 2023-08-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/def.webp', upload_to='images/'),
        ),
    ]
