# Generated by Django 4.2.4 on 2023-08-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_context_postcomments_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComments',
            new_name='PostComment',
        ),
    ]
