# Generated by Django 4.2.4 on 2023-08-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
