# Generated by Django 4.2.4 on 2023-08-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="images/ppan.jpg", upload_to="images/"),
        ),
    ]
