# Generated by Django 4.2.4 on 2023-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('programing language', 'programing language'), ('DataBase', 'DataBase'), ('artificial intelligence', 'artificial intelligence'), ('internet of things', 'internet of things')], max_length=256),
        ),
    ]
