# Generated by Django 4.2.4 on 2023-08-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.TextField(choices=[('fo', 'food'), ('he', 'helth'), ('ca', 'care and beauty'), ('fit', 'fitness')], max_length=128),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
