# Generated by Django 4.2.4 on 2023-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_content_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.TextField(choices=[('food', 'food'), ('health', 'health'), ('care and beauty', 'care and beauty'), ('fitness', 'fitness')], max_length=128),
        ),
    ]
