# Generated by Django 4.2.4 on 2023-08-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_upload',
            field=models.ImageField(default='images/default.pnj', upload_to='images/'),
        ),
    ]
